config/routes.rb
Rails.application.routes.draw do
  devise_for :candidates
  devise_for :headhunters
  root to: 'home#index'
  resources :vacancies do
    get 'search', on: :collection
    post 'finalize', on: :member
  end
  resources :entries do
    post 'apply', on: :member
    post 'feature', on: :member
    post 'unfeature', on: :member
    get 'registered', on: :collection
    get 'reject', on: :member
  end
  resources :profiles, only: [:new, :create, :edit, :update, :show]
  resources :comments do
    post 'post', on: :member
  end
  resources :feedbacks do
    post 'decline', on: :member
  end
  resources :entries do
    resources :proposals do
      get 'confirm', on: :member
      get 'refuse', on: :member
    end
  end
  resources :reports do
    post 'positive', on: :member
    post 'negative', on: :member
  end
  namespace :api do
    namespace :v1 do
      resources :vacancies, only: %i[show index]
    end
  end
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  validates :title, :description, :skill, :wage, :role, :end_date, :location,
            presence: true
  validate :end_date_must_be_greater_than_today
  belongs_to :headhunter
  has_many :entries
  has_many :candidates, through: :registrations
  enum status: {avaiable: 0, finalized: 5}

  def end_date_must_be_greater_than_today
    if end_date <= Date.current
      errors.add(:end_date, 'deve ser maior que data de fim')
    end
  end

#  after_commit do
#  delay(run_at: end_date + 1.day).expire!
#  end
#  def expire!
#    finalized! unless finalized?
#  end
end

app/controllers/api/v1/vacancies_controller.rb
class Api::V1::VacanciesController < Api::V1::ApiController

  def show
    @vacancy = Vacancy.find(params[:id])
    render json: @vacancy
  end

  def index
    @vacancies = Vacancy.all
    render json: @vacancies
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :authenticate_headhunter!, only: [:new,
                                                  :create,
                                                  :edit,
                                                  :update,
                                                  :destroy,
                                                  :finalize]
  before_action :redirect_candidate_to_new_profile, only: [:index,
                                                           :show,
                                                           :search]
  before_action :vacancy_expiration_show, only: [:show]
  before_action :vacancy_expiration_index, only: [:index]
  before_action :check_if_there_are_entries, only: [:destroy]


  def index
    if headhunter_signed_in?
      @headhunter_vacancies = current_headhunter.vacancies.all
    end
    @vacancies = Vacancy.all
  end

  def show
    @vacancy = Vacancy.find(params[:id])
    @entry = Entry.new
  end

  def new
    @vacancy = Vacancy.new
  end

  def create
    @vacancy = current_headhunter.vacancies.create(vacancy_params)
    if @vacancy.save
      @vacancy.avaiable!
      redirect_to @vacancy, notice: 'Vaga cadastrada com sucesso'
    else
      render :new
    end
  end

  def finalize
    @vacancy = Vacancy.find(params[:id])
    @vacancy.finalized!
    @vacancy.save
    redirect_to vacancies_path, notice: 'Vaga encerrada com sucesso'
  end

  def destroy
    @vacancy = Vacancy.find(params[:id])
    @vacancy.destroy
    redirect_to vacancies_path
  end

  def search
    @vacancies = Vacancy.where('title like ?', "%#{params[:q]}%")
    render :index
  end

  private

  def vacancy_params
  params.require(:vacancy).permit(:title, :description, :skill, :wage, :role,
                                  :end_date, :location)
  end

  def redirect_candidate_to_new_profile
    if candidate_signed_in?
      unless current_candidate.complete?
      redirect_to new_profile_path, notice: "Complete seu perfil para ter \
acesso a todas as funcionalidades"
      end
    end
  end

  def vacancy_expiration_index
   @vacancies = Vacancy.all
   @vacancies.each do |vacancy|
     if Date.current > vacancy.end_date
       vacancy.finalized!
     end
   end
 end
 def vacancy_expiration_show
   @vacancy = Vacancy.find(params[:id])
   if Date.current > @vacancy.end_date
     @vacancy.finalized!
   end
 end

 def check_if_there_are_entries
   @vacancy = Vacancy.find(params[:id])
   if @vacancy.entries.any?
     flash[:notice] = 'Não é possível deletar uma vaga que ja possui aplicações'
     redirect_to vacancies_path
   end
 end
end

app/views/vacancies/index.html.erb
<h3>Minhas Vagas</h3>
<% if @vacancies.avaiable.empty? %>
  <p>Nenhuma vaga disponível no momento.</p>
<% end %>

<% if candidate_signed_in? %>

  <%= form_with(url: search_vacancies_path, local: true, method: :get) do %>
    <%= label_tag :q, 'Buscar vaga por título' %>
    <%= text_field_tag :q %>
    <%= submit_tag 'Buscar' %>
  <% end %>

  <dl>
  <% @vacancies.each do |vacancy| %>
    <% unless vacancy.finalized? %>
      <dt>Título:</dt>
      <dd><%= link_to vacancy.title, vacancy %></dd>
      <dt>Descrição:</dt>
      <dd><%= vacancy.description %> </dd>
      <dt>Habilidades necessárias:</dt>
      <dd><%= vacancy.skill %> </dd>
      <dt>Faixa salarial (R$):</dt>
      <dd><%= vacancy.wage %></dd>
      <dt>Nível do cargo:</dt>
      <dd><%= vacancy.role %></dd>
      <dt>Data limite de inscriçōes:</dt>
      <dd><%= vacancy.end_date.strftime('%d/%m/%Y') %></dd>
      <dt>Região:</dt>
      <dd><%= vacancy.location %></dd>
      <p>Esta vaga possui <%=vacancy.entries.count %> inscriçōes no momento</p>
      <hr>
    <% end %>
  <% end %>
  </dl>
<% end %>

<% if headhunter_signed_in? %>
<dl>
  <% @headhunter_vacancies.each do |vacancy| %>
    <%if vacancy.finalized? %>
      <p>Status: Inscrições encerradas</p>
    <% elsif vacancy.avaiable? %>
      <p>Status: Inscrições abertas</p>
    <% end %>
    <dt>Título:</dt>
    <dd><%= link_to vacancy.title, vacancy %></dd>
    <dt>Descrição:</dt>
    <dd><%= vacancy.description %> </dd>
    <p>Esta vaga possui <%=vacancy.entries.count %> inscriçōes no momento</p>
    <hr>
  <% end %>
</dl>
<% end %>

app/views/vacancies/new.html.erb
<h1>Registrar vaga</h1>

<% if @vacancy.errors.any? %>
  <p>Você deve corrigir os seguintes erros:</p>
  <ul>
  <% @vacancy.errors.full_messages.each do |message| %>
    <li> <%= message %> </li>
  <% end %>
  </ul>
<% end %>

<%= form_with model: @vacancy, local: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :skill %>
  <%= f.text_field :skill %>
  <%= f.label :wage %>
  <%= f.text_field :wage %>
  <%= f.label :role %>
  <%= f.text_field :role %>
  <%= f.label :end_date %>
  <%= f.date_field :end_date %>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <%= f.submit 'Registrar vaga' %>
<% end %>

app/views/vacancies/registered.html.erb
<% if candidate_signed_in? %>
  <h1>Minhas vagas</h1>
  <dl>
  <% @entries.each do |entry| %>
    <% if entry.avaiable? %>
      <dt>Status:</dt>
      <dd>Aguardando resposta</dd>
      <dt>Título:</dt>
      <dd><%= entry.vacancy.title %></dd>
      <dt>Descrição:</dt>
      <dd><%= entry.vacancy.description %> </dd>
      <dt>Habilidades necessárias:</dt>
      <dd><%= entry.vacancy.skill %> </dd>
      <dt>Faixa salarial (R$):</dt>
      <dd><%= entry.vacancy.wage %></dd>
      <dt>Nível do cargo:</dt>
      <dd><%= entry.vacancy.role %></dd>
      <dt>Data limite de inscriçōes:</dt>
      <dd><%= entry.vacancy.end_date.strftime('%d/%m/%Y') %></dd>
      <dt>Região:</dt>
      <dd><%= entry.vacancy.location %></dd>
    <% elsif entry.rejected? %>
      <dt>Status:</dt>
      <dd>Recusada</dd>
      <dt>Título:</dt>
      <dd><%= entry.vacancy.title %></dd>
      <dt>Feedback de <%= entry.vacancy.headhunter.name %></dt>
      <dd><%= entry.feedback.body %></dd>
    <% end %>
  <% end %>
  </dl>
<% end %>

<% if headhunter_signed_in? %>
  <h1>Aplicaçōes para vagas</h1>
  <dl>
  <% @entries.each do |entry| %>
    <%if entry.featured? %>
      <p>⭐</p>
    <% end %>
    <% if entry.rejected? %>
      <dt>Feedback:</dt>
      <dd><%= entry.feedback.body %> </dd>
    <% end %>
    <dt>Título:</dt>
    <dd><%= entry.vacancy.title %></dd>
    <dt>Nome completo:</dt>
    <dd><%= entry.profile.full_name %></dd>
    <dt>Nome social:</dt>
    <dd><%= entry.profile.social_name %> </dd>
    <dt>Data de nascimento:</dt>
    <dd><%= entry.profile.birth_date.strftime('%d/%m/%Y') %> </dd>
    <dt>Formação acadêmica:</dt>
    <dd><%= entry.profile.education %></dd>
    <dt>Descrição:</dt>
    <dd><%= entry.profile.description %></dd>
    <dt>Experiências profissionais:</dt>
    <dd><%= entry.profile.experience %></dd>
    <dt>Mensagem do candidato:</dt>
    <dd><%= entry.description %></dd>
    <% unless entry.comments.empty? %>
      <dt>Comentários do anunciante:</dt>
      <% entry.comments.each do |comment| %>
        <dd><%= comment.body %> </dd>
        <dd>Enviado em: <%= comment.comment_date %></dd>
      <% end %>
    <% end %>

    <%= form_with model: @comment, url: post_comment_path(entry), method: :post do |f| %>
      <%= f.label :body, 'Comente este perfil' %>
      <%= f.text_field :body %>
      <%= f.submit 'Enviar comentário' %>
    <% end %>
    <% unless entry.rejected? %>
      <% unless entry.featured? %>
        <p><%= link_to 'Marcar perfil como destaque', feature_vacancy_path(entry), method: :post %></p>
      <% end %>
      <p><%= link_to 'Enviar proposta para candidato', new_entry_proposal_path(entry) %>
      <p><%= link_to 'Rejeitar participação', reject_vacancy_path(entry) %></p>
    <% end %>
  <% end %>
  </dl>
<% end %>

app/views/vacancies/show.html.erb
<dl>
  <dt>Vaga:</dt>
  <dd><%= @vacancy.title %></dd>
  <dt>Descrição:</dt>
  <dd><%= @vacancy.description %> </dd>
  <dt>Habilidades necessárias:</dt>
  <dd><%= @vacancy.skill %> </dd>
  <dt>Faixa salarial (R$):</dt>
  <dd><%= @vacancy.wage %></dd>
  <dt>Nível do cargo:</dt>
  <dd><%= @vacancy.role %></dd>
  <dt>Data limite de inscriçōes:</dt>
  <dd><%= @vacancy.end_date.strftime('%d/%m/%Y') %></dd>
  <dt>Região:</dt>
  <dd><%= @vacancy.location %></dd>
</dl>

<% if candidate_signed_in? %>
  <%= form_with model: @entry, url: apply_entry_path(@vacancy), method: :post do |f| %>
    <%= f.label :description, 'Conte-nos mais sobre você!' %>
    <%= f.text_field :description %>
    <%= f.submit 'Aplicar-se à vaga' %>
  <% end %>
<% end %>

<% if headhunter_signed_in? %>
  <p><%= link_to 'Encerrar inscrições para esta vaga', finalize_vacancy_path(@vacancy), method: :post  %></p><br>
  <p><%= link_to 'Deletar vaga', vacancy_path(@vacancy), :data => {:method => "delete"} %></p>
<% end %>