config/routes.rb
Rails.application.routes.draw do
  devise_for :candidates
  devise_for :headhunters
  root to: 'home#index'
  resources :vacancies do
    get 'search', on: :collection
    post 'finalize', on: :member
  end
  resources :entries do
    post 'apply', on: :member
    post 'feature', on: :member
    post 'unfeature', on: :member
    get 'registered', on: :collection
    get 'reject', on: :member
  end
  resources :profiles, only: [:new, :create, :edit, :update, :show]
  resources :comments do
    post 'post', on: :member
  end
  resources :feedbacks do
    post 'decline', on: :member
  end
  resources :entries do
    resources :proposals do
      get 'confirm', on: :member
      get 'refuse', on: :member
    end
  end
  resources :reports do
    post 'positive', on: :member
    post 'negative', on: :member
  end
  namespace :api do
    namespace :v1 do
      resources :vacancies, only: %i[show index]
    end
  end
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :candidate
  belongs_to :entry
  belongs_to :headhunter
  has_one :report
  enum status: {avaiable: 0, accepted: 5, refused: 10}
  validates :start_date, :workload, :benefits, :wage, :details, presence: true
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :authenticate_headhunter!, only: [:new, :create]
  before_action :authenticate_candidate!, only: [:confirm, :refuse]


  def index
  end

  def new
    @proposal = Proposal.new
    @entry = Entry.find(params[:entry_id])
  end

  def create
    @entry = Entry.find(params[:entry_id])
    if @entry.proposal.nil?
      @headhunter = current_headhunter
      @candidate = @entry.candidate
      @proposal = @entry.create_proposal(proposals_params)
      if @proposal.save
        @proposal.avaiable!
        redirect_to entry_proposals_path, notice: 'Proposta enviada!'
      else
        render :new
      end
    elsif @entry.proposal.present?
      redirect_to entry_proposals_path, notice: "Você ja enviou uma proposta \
para esta aplicação"
    end
  end

  def show
    @proposal = Proposal.find(params[:id])
  end

  def confirm
    @proposal = Proposal.find(params[:id])
    @report = Report.new
  end

  def refuse
    @proposal = Proposal.find(params[:id])
    @report = Report.new
  end

  private

  def proposals_params
    headhunter = current_headhunter
    params.require(:proposal).permit(:start_date,
                                     :workload,
                                     :benefits,
                                     :details,
                                     :wage).merge(candidate_id: @candidate.id,
                                                  headhunter: headhunter)

  end
end

app/views/proposals/_candidate_proposal_index.html.erb
<dl>
<% current_candidate.proposals.each do |proposal| %>
  <% if proposal.accepted? %>
    <dt>Status:</dt>
    <dd>Proposta aceita ✅</dd>
    <dt>Vaga:</dt>
    <dd><%= link_to proposal.entry.vacancy.title, entry_proposal_path(proposal, proposal.entry) %></dd>
    <dt>Candidato:</dt>
    <dd><%= proposal.entry.candidate.profile.social_name %></dd>
    <% unless proposal.report.blank? %>
      <dt>Mensagem adicional:</dt>
      <dd><%= proposal.report.body %></dd>
    <% end %>
  <% elsif proposal.refused? %>
    <dt>Status:</dt>
    <dd>Proposta recusada ❌</dd>
    <dt>Vaga:</dt>
    <dd><%= link_to proposal.entry.vacancy.title, entry_proposal_path(proposal, proposal.entry) %></dd>
    <dt>Candidato:</dt>
    <dd><%= proposal.entry.candidate.profile.social_name %></dd>
    <% unless proposal.report.blank? %>
      <dt>Mensagem adicional:</dt>
      <dd><%= proposal.report.body %></dd>
    <% end %>
  <% else %>
    <dt>Status:</dt>
    <dd>Aguardando sua resposta 💬</dd>
    <dt>Vaga:</dt>
    <dd><%= link_to proposal.entry.vacancy.title, entry_proposal_path(proposal, proposal.entry) %></dd>
    <dt>Candidato:</dt>
    <dd><%= proposal.entry.candidate.profile.social_name %></dd>
  <% end %>
  <hr>
<% end %>
</dl>

app/views/proposals/_headhunter_proposal_index.html.erb
<dl>
<% current_headhunter.proposals.each do |proposal| %>
  <% if proposal.accepted? %>
    <dt>Status:</dt>
    <dd>Proposta aceita ✅</dd>
    <dt>Vaga:</dt>
    <dd><%= link_to proposal.entry.vacancy.title, entry_proposal_path(proposal, proposal.entry) %></dd>
    <dt>Candidato:</dt>
    <dd><%= proposal.entry.candidate.profile.social_name %></dd>
    <% unless proposal.report.blank? %>
      <dt>Mensagem adicional:</dt>
      <dd><%= proposal.report.body %></dd>
    <% end %>
  <% elsif proposal.refused? %>
    <dt>Status:</dt>
    <dd>Proposta recusada ❌</dd>
    <dt>Vaga:</dt>
    <dd><%= link_to proposal.entry.vacancy.title, entry_proposal_path(proposal, proposal.entry) %></dd>
    <dt>Candidato:</dt>
    <dd><%= proposal.entry.candidate.profile.social_name %></dd>
    <% unless proposal.report.blank? %>
      <dt>Mensagem adicional:</dt>
      <dd><%= proposal.report.body %></dd>
    <% end %>
  <% else %>
    <dt>Status:</dt>
    <dd>Aguardando resposta 💬</dd>
    <dt>Vaga:</dt>
    <dd><%= link_to proposal.entry.vacancy.title, entry_proposal_path(proposal, proposal.entry) %></dd>
    <dt>Candidato:</dt>
    <dd><%= proposal.entry.candidate.profile.social_name %></dd>
  <% end %>
  <hr>
<% end %>
</dl>

app/views/proposals/_proposal_index.html.erb
<dl>
<% @proposals.each do |proposal| %>
  <% if proposal.accepted? %>
    <dt>Status:</dt>
    <dd>Proposta aceita ✅</dd>
    <dt>Vaga:</dt>
    <dd><%= link_to proposal.entry.vacancy.title, entry_proposal_path(proposal, proposal.entry) %></dd>
    <dt>Candidato:</dt>
    <dd><%= proposal.entry.candidate.profile.social_name %></dd>
    <% unless proposal.report.blank? %>
      <dt>Mensagem adicional:</dt>
      <dd><%= proposal.report.body %></dd>
    <% end %>
  <% elsif proposal.refused? %>
    <dt>Status:</dt>
    <dd>Proposta recusada ❌</dd>
    <dt>Vaga:</dt>
    <dd><%= link_to proposal.entry.vacancy.title, entry_proposal_path(proposal, proposal.entry) %></dd>
    <dt>Candidato:</dt>
    <dd><%= proposal.entry.candidate.profile.social_name %></dd>
    <% unless proposal.report.blank? %>
      <dt>Mensagem adicional:</dt>
      <dd><%= proposal.report.body %></dd>
    <% end %>
  <% else %>
    <dt>Status:</dt>
    <dd>Aguardando sua resposta 💬</dd>
    <dt>Vaga:</dt>
    <dd><%= link_to proposal.entry.vacancy.title, entry_proposal_path(proposal, proposal.entry) %></dd>
    <dt>Candidato:</dt>
    <dd><%= proposal.entry.candidate.profile.social_name %></dd>
  <% end %>
  <hr>
<% end %>
</dl>

app/views/proposals/confirm.html.erb
<h2>Aceitar proposta</h2>
<p>Você tem certeza que deseja aceitar esta proposta? Ao clicar em "Confirmar
   e aceitar proposta", todas as suas aplicaçōes em outras vagas terão o status
   automaticamente trocado para "Rejeitada".</p>

   <%= form_with model: @report, url: positive_report_path(@proposal), method: :post do |f| %>
     <%= f.label :body, 'Mensagem adicional (opcional)' %>
     <%= f.text_field :body %>
     <%= f.submit 'Confirmar e aceitar proposta' %>
   <% end %>

app/views/proposals/index.html.erb
<% if headhunter_signed_in? %>
  <h1>Propostas enviadas</h1>
  <%= render partial: "headhunter_proposal_index", locals: {proposals: @proposals} %>
<% end %>

<% if candidate_signed_in? %>
  <h1>Propostas recebidas</h1>
 <%= render partial: "candidate_proposal_index", locals: {proposals: @proposals} %>
<% end %>

app/views/proposals/new.html.erb
<h3>Enviar proposta ao usuário</h3>

<% if @proposal.errors.any? %>
  <p>Você deve corrigir os seguintes erros:</p>
  <ul>
  <% @proposal.errors.full_messages.each do |message| %>
    <li> <%= message %> </li>
  <% end %>
  </ul>
<% end %>

<%= form_with model: @proposal, url: entry_proposals_path(@entry) do |f| %>
  <%= f.label :start_date %>
  <%= f.date_field :start_date %>
  <%= f.label :workload %>
  <%= f.text_field :workload %>
  <%= f.label :benefits %>
  <%= f.text_field :benefits %>
  <%= f.label :wage %>
  <%= f.text_field :wage %>
  <%= f.label :details %>
  <%= f.text_area :details %>
  <%= f.submit 'Enviar proposta' %>
<% end %>

app/views/proposals/refuse.html.erb
<h2>Recusar proposta</h2>
<p>Você tem certeza que deseja recusar esta proposta? Esta ação não pode ser desfeita.</p>
   <%= form_with model: @report, url: negative_report_path(@proposal), method: :post do |f| %>
     <%= f.label :body, 'Mensagem adicional (opcional)' %>
     <%= f.text_field :body %>
     <%= f.submit 'Confirmar rejeição da proposta' %>
   <% end %>

app/views/proposals/show.html.erb
<h3><%= @proposal.entry.vacancy.title %></h3>
<dl>
  <dt>Empresa:</dt>
  <dd><%= @proposal.entry.vacancy.headhunter.name %></dd>
  <dt>Proposta enviada para:</dt>
  <dd><%= @proposal.entry.candidate.profile.social_name %></dd>
  <dt>Data prevista para início:</dt>
  <dd><%= @proposal.start_date.strftime('%d/%m/%Y') %></dd>
  <dt>Carga horária:</dt>
  <dd><%= @proposal.workload %> </dd>
  <dt>Benefícios:</dt>
  <dd><%= @proposal.benefits %> </dd>
  <dt>Salário:</dt>
  <dd><%= @proposal.wage %></dd>
  <dt>Detalhes:</dt>
  <dd><%= @proposal.details %></dd>
</dl>

<% if candidate_signed_in? %>
  <% unless @proposal.refused? || @proposal.accepted? %>
    <p><%= link_to 'Aceitar proposta', confirm_entry_proposal_path(@proposal) %></p>
    <p><%= link_to 'Rejeitar proposta', refuse_entry_proposal_path(@proposal) %></p><br>
  <% end %>
  <p><%= link_to 'Voltar', entry_proposals_path(current_candidate) %></p>
<% end %>