config/routes.rb
Rails.application.routes.draw do
  devise_for :candidates
  devise_for :headhunters
  root to: 'home#index'
  resources :vacancies do
    get 'search', on: :collection
    post 'finalize', on: :member
  end
  resources :entries do
    post 'apply', on: :member
    post 'feature', on: :member
    post 'unfeature', on: :member
    get 'registered', on: :collection
    get 'reject', on: :member
  end
  resources :profiles, only: [:new, :create, :edit, :update, :show]
  resources :comments do
    post 'post', on: :member
  end
  resources :feedbacks do
    post 'decline', on: :member
  end
  resources :entries do
    resources :proposals do
      get 'confirm', on: :member
      get 'refuse', on: :member
    end
  end
  resources :reports do
    post 'positive', on: :member
    post 'negative', on: :member
  end
  namespace :api do
    namespace :v1 do
      resources :vacancies, only: %i[show index]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LaborCompassTreinadev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <p>
      <% if headhunter_signed_in? %>
        <%= link_to 'Home', root_path %>
        <%= link_to 'Editar Perfil', edit_headhunter_registration_path %>
        <%= link_to 'Cadastrar nova vaga', new_vacancy_path %>
        <%= link_to 'Minhas vagas', vacancies_path %>
        <%= link_to 'Aplicaçōes recebidas', registered_entries_path %>
        <%= link_to 'Minhas propostas', entry_proposals_path(current_headhunter) %>
        <%= link_to 'Sair', destroy_headhunter_session_path, method: :delete %></p>
      <% elsif candidate_signed_in? %>
          <%= link_to 'Home', root_path %>
          <%= link_to 'Vagas disponíveis', vacancies_path %>
          <%= link_to 'Minhas vagas', registered_entries_path %>
          <%= link_to 'Propostas recebidas', entry_proposals_path(current_candidate) %>
          <% unless current_candidate.complete? %>
            <%= link_to 'Completar perfil', new_profile_path %>
            <% else %>
              <%= link_to 'Meu perfil', profile_path(current_candidate) %>
        <% end %>
          <%= link_to 'Sair', destroy_candidate_session_path, method: :delete %></p>
      <% else %>
          <%= link_to 'Entrar como Headhunter', new_headhunter_session_path %></p>
          <%= link_to 'Entrar como Candidato', new_candidate_session_path %>
      <% end %>
      </p>
    </nav>
    <%= notice %>
    <%= alert %>
    <%= yield %>
  </body>
</html>